== Практическая работа №4 - Создание матрицы требований
:listing-number: 0
:figure-number: 0
:table-number: 0

*Цель работы:*

Получить навыки по определению нефункциональных требований для своей
разработки, а также по раскрытию наполнения требований, их источников и
критериев проверки, путем формализации всей информации о требованиях в виде
матрицы требований.

*Задание:*

1. Определить нефункциональные требования для своей разработки. 
Нефункциональных требований должно быть не менее 3 для каждого из 
выбранных “разделов” и их составляют все члены команды.

2. Сформировать матрицу требований для своей разработки. За матрицу 
требований отвечает технический писатель.

3. Сформировать единый отчет по блоку практик (с 1 по 4 практику).

*Ход работы:*

*Нефункциональные требования:*

.Нефункциональные требования
[cols="1,1", width="100%",caption="Таблица 1 - "]
|===
| *Тип требования* | *Содержание требования*
| *Технические ограничения* | 
Конфигурация должна быть кроссплатформенной и
работать на различных системах, которые чаще всего
используются в рамках работы: Windows, Linux, Mac OS.
Для работы ИС в рамках сети (например сети автомастерских в
городе), необходимо интернет-подключение и централизированный сервер для
хранения и обработки данных

| *Производительность* | 
AAA
|===

*Матрица требования для информационной системы:*

В таблице 2 представлена матрица требований к веб приложению.

.Матрица требований к веб приложению
[cols="1,3,4,2,2,3", width="100%",caption="Таблица 2 - "]
|===
| *№* | *Требование* | *Суть* | *Автор* | *Ссылки* | *Критерий проверки*
| 1 | Регистрация пользователя | "ИС должна иметь функцию регистрации пользователя" 
| Тимофеев С.А. | https://ya.ru | Регистрация нового пользователя
| 2 | AAA | BBB 
| CCC | DDD | EEE
|===

В таблице 3 представлена матрица требований к правовым нормам регулирования 
деятельности приложения.

.Матрица требований к правовым нормам регулирования деятельности
[cols="1,3,4,2,2,3", width="100%",caption="Таблица 2 - "]
|===
| *№* | *Требование* | *Суть* | *Автор* | *Ссылки* | *Критерий проверки*
| 1 | Регистрация пользователя | "ИС должна иметь функцию регистрации пользователя" 
| Тимофеев С.А. | https://ya.ru | Регистрация нового пользователя
| 2 | AAA | BBB 
| CCC | DDD | EEE
|===

*Заключение:*

Подводя итог, можно сделать вывод о том, что при выполнении 1-4 практик
была выбрана и проанализирована предметная область, а так же распределены
задачи членов команды, определены функциональные и пользовательские
требования для будущего продукта, проведено начальное моделирование
предметной области, а конкретно составлены портреты пользователя и ЦА, а также при помощи инструментальных средств 
моделирования приведены различные видыдиаграмм, также были составлены нефункциональные требования и матрица общих
требований (чаще всего это требования к обеспечению бизнес-процессов) к
продукту. Были получены практически и теоретические навыки по данным
разделам и изучена предметная область, также в рамках дополнения был приведен
отрывок технического задания сделанного по ГОСТ 34.602-89 «Техническое
задание на создание автоматизированной системы».

<<<